// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/andreyfadeev/api/v1/add_service.proto
// Protobuf Java Version: 4.27.0

package com.andreyfadeev.api.v1;

public interface AddResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.andreyfadeev.api.v1.AddResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sum = 1 [json_name = "sum"];</code>
   * @return The sum.
   */
  long getSum();
}
