// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/andreyfadeev/api/v1/add_service.proto
// Protobuf Java Version: 4.27.0

package com.andreyfadeev.api.v1;

public interface AddRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.andreyfadeev.api.v1.AddRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 x = 1 [json_name = "x"];</code>
   * @return The x.
   */
  long getX();

  /**
   * <code>int64 y = 2 [json_name = "y"];</code>
   * @return The y.
   */
  long getY();
}
