// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/andreyfadeev/api/v1/hello_service.proto
// Protobuf Java Version: 4.27.0

package com.andreyfadeev.api.v1;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.andreyfadeev.api.v1.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1 [json_name = "greeting"];</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1 [json_name = "greeting"];</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
