// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/andreyfadeev/api/v1/hello_service.proto
// Protobuf Java Version: 4.27.0

package com.andreyfadeev.api.v1;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.andreyfadeev.api.v1.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string first_name = 1 [json_name = "firstName"];</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 1 [json_name = "firstName"];</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 2 [json_name = "lastName"];</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 2 [json_name = "lastName"];</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
