// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/com/kroo/api/v1/hello_service.proto
// Protobuf Java Version: 4.27.0

package com.kroo.api.v1;

public final class HelloServiceOuterClass {
  private HelloServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      HelloServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kroo_api_v1_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kroo_api_v1_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kroo_api_v1_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kroo_api_v1_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)proto/com/kroo/api/v1/hello_service.pr" +
      "oto\022\017com.kroo.api.v1\"J\n\014HelloRequest\022\035\n\n" +
      "first_name\030\001 \001(\tR\tfirstName\022\033\n\tlast_name" +
      "\030\002 \001(\tR\010lastName\"+\n\rHelloResponse\022\032\n\010gre" +
      "eting\030\001 \001(\tR\010greeting2V\n\014HelloService\022F\n" +
      "\005hello\022\035.com.kroo.api.v1.HelloRequest\032\036." +
      "com.kroo.api.v1.HelloResponseB\023\n\017com.kro" +
      "o.api.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_kroo_api_v1_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kroo_api_v1_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_kroo_api_v1_HelloRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_com_kroo_api_v1_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kroo_api_v1_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_kroo_api_v1_HelloResponse_descriptor,
        new java.lang.String[] { "Greeting", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
